export const STUDENTSIGNUP = "STUDENTSIGNUP";
export const STUDENTSIGNUP_ERRORS ="STUDENTSIGNUP_ERRORS";
export const STUDENTLOGIN ="STUDENTLOGIN";
export const STUDENTLOGIN_ERRORS ="STUDENTLOGIN_ERRORS";